<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Marknexia.Core\Marknexia.Core.csproj" />
    <ProjectReference Include="..\Marknexia.Files\Marknexia.Files.csproj" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Marknexia.Infrastructure.Tests" />
  </ItemGroup>
</Project>
